spring:
  application:
    name: reactive-postgres

  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}

  sql:
    init:
      mode: always

server:
  port: 8033

logging:
  level:
    org.springframework.r2dbc.core: DEBUG

