spring:
  application:
    name: reactive-postgres

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/reactive_db
    username: postgres
    password: 1234

  sql:
    init:
      mode: always

server:
  port: 8033

logging:
  level:
    org.springframework.r2dbc.core: DEBUG

